In [1]:
import torch as t

In [2]:
a = t.Tensor(2, 3)
a

tensor([[3.2721e+21, 1.0624e+21, 5.2708e-08],
        [2.1159e-07, 5.4174e-05, 5.3696e-05]])

In [3]:
b = t.tensor([[1, 2, 3], [2, 3, 4]])
b.tolist()

[[1, 2, 3], [2, 3, 4]]

In [4]:
print(f'type(b): {type(b)}')

type(b): <class 'torch.Tensor'>


In [5]:
b.numel()

6

In [6]:
c = t.Tensor(b.size())
c

tensor([[1.6926e+22, 5.4366e+22, 1.6898e-04],
        [8.5458e-07, 2.1121e+20, 1.7000e+22]])

### 调整tensor形状

In [7]:
a = t.arange(0, 6)
a

tensor([0, 1, 2, 3, 4, 5])

In [8]:
b = a.view(2, 3)
print(f'a: {a}\n\n b: {b}')

a: tensor([0, 1, 2, 3, 4, 5])

 b: tensor([[0, 1, 2],
        [3, 4, 5]])


In [9]:
c = a.view(-1, 3)
print(f'a: {a}\n\nc: {c}')

a: tensor([0, 1, 2, 3, 4, 5])

c: tensor([[0, 1, 2],
        [3, 4, 5]])


In [10]:
a[1] = 0
print(f'a: {a}\n\nb: {b}\n\nc: {c}')

a: tensor([0, 0, 2, 3, 4, 5])

b: tensor([[0, 0, 2],
        [3, 4, 5]])

c: tensor([[0, 0, 2],
        [3, 4, 5]])


In [11]:
d = b.unsqueeze(1)
d, d.size()

(tensor([[[0, 0, 2]],
 
         [[3, 4, 5]]]),
 torch.Size([2, 1, 3]))

In [12]:
e = b.view(1, 1, 2, 1, 3)
f = e.squeeze(0)
f, f.size()
# e, e.size()

(tensor([[[[0, 0, 2]],
 
          [[3, 4, 5]]]]),
 torch.Size([1, 2, 1, 3]))

In [13]:
e.squeeze()

tensor([[0, 0, 2],
        [3, 4, 5]])

In [14]:
e = b.view(1, 1, 2, 1, 3)
f = e.squeeze(0)  # 压缩第0维的“1”，某一维度为“1”才能压缩，如果第0维的维度是“2”如(2,1,1,1,3)则无法亚索第0维
f, f.size()

(tensor([[[[0, 0, 2]],
 
          [[3, 4, 5]]]]),
 torch.Size([1, 2, 1, 3]))

In [15]:
a = t.arange(0, 16).view(4, 4)
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [16]:
index = t.LongTensor([[0, 1, 2, 3]])
print(f'index: {index}')
a.gather(0, index)

index: tensor([[0, 1, 2, 3]])


tensor([[ 0,  5, 10, 15]])

In [17]:
# 选取反对角线上的元素
index = t.LongTensor([[3, 2, 1, 0]])  # .t()是转置
a.gather(0, index)

tensor([[12,  9,  6,  3]])

In [18]:
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [19]:
x = t.arange(0, 27).view(3, 3, 3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])

In [20]:
x[[1, 2], [1, 2], [2, 0]]  # x[1,1,2] 和 x[2,2,0]

tensor([14, 24])

In [21]:
t.set_default_tensor_type('torch.DoubleTensor')

In [22]:
a = t.Tensor(2, 3)
a, a.type()

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 'torch.DoubleTensor')

In [23]:
b = a.int()
b, b.type()

(tensor([[0, 0, 0],
         [0, 0, 0]], dtype=torch.int32),
 'torch.IntTensor')

In [24]:
c = a.type_as(b)
c, c.type()

(tensor([[0, 0, 0],
         [0, 0, 0]], dtype=torch.int32),
 'torch.IntTensor')

In [25]:
d = a.new(2, 3)
d, d.type()

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 'torch.DoubleTensor')

In [26]:
t.set_default_tensor_type('torch.FloatTensor')  # 恢复之前的默认设置

In [27]:
b = t.ones(2, 3)
a = t.zeros(2, 3)
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [28]:
b.sum(dim=0), b.sum(dim=0, keepdim=True)  # 前者输出形状是(3)，后者输出形状是(1,3)

(tensor([2., 2., 2.]), tensor([[2., 2., 2.]]))

In [29]:
a = t.arange(0, 6).view(2, 3)
a

tensor([[0, 1, 2],
        [3, 4, 5]])

In [30]:
a.cumsum(dim=1)

tensor([[ 0,  1,  3],
        [ 3,  7, 12]])

### tensor & ndarray

In [31]:
import numpy as np

a = np.ones((2, 3), dtype=np.float32)
a

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [32]:
b = t.from_numpy(a)
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [33]:
b = t.Tensor(a)
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [34]:
a[0, 1] = 100
c = b.numpy()
c

array([[  1., 100.,   1.],
       [  1.,   1.,   1.]], dtype=float32)

In [35]:
a = t.ones(3, 2)
b = t.zeros(2, 3, 1)

In [36]:
b, b.expand(2, 3, 2)

(tensor([[[0.],
          [0.],
          [0.]],
 
         [[0.],
          [0.],
          [0.]]]),
 tensor([[[0., 0.],
          [0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.],
          [0., 0.]]]))

In [37]:
a.unsqueeze(0).expand(2, 3, 2), a.shape

(tensor([[[1., 1.],
          [1., 1.],
          [1., 1.]],
 
         [[1., 1.],
          [1., 1.],
          [1., 1.]]]),
 torch.Size([3, 2]))

In [39]:
print(t.cuda.is_available())

True


## Autograd


### Variable

In [2]:
import torch as t
from torch.autograd import Variable as V

In [3]:
a = V(t.ones(3, 4), requires_grad=True)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], requires_grad=True)

In [4]:
b = V(t.zeros(3, 4))
b

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
c = a.add(b)
c

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], grad_fn=<AddBackward0>)

In [6]:
a.requires_grad, b.requires_grad, c.requires_grad

(True, False, True)

In [9]:
d = c.sum()
d.backward()

In [10]:
a.grad

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [11]:
a.is_leaf, b.is_leaf, c.is_leaf

(True, True, False)

In [12]:
c.retain_grad()
c.grad is None

True

In [13]:
c

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], grad_fn=<AddBackward0>)

In [14]:
def f(x):
    y = x**2 * t.exp(x)
    return y

def gradf(x):
    dx = 2*x*t.exp(x) + x**2*t.exp(x)
    return dx

x = V(t.randn(3, 4), requires_grad=True)
y = f(x)
y

tensor([[1.4831e+01, 3.6706e-01, 1.3936e-01, 2.6639e-03],
        [3.9522e-01, 5.3491e-01, 2.0241e-02, 6.5490e-01],
        [4.6668e-01, 6.7475e-02, 2.7539e+00, 2.9840e+00]],
       grad_fn=<MulBackward0>)

In [15]:
y_grad_variables = t.ones(y.size())
y.backward(y_grad_variables)
x.grad

tensor([[32.5879, -0.3687,  1.0148,  0.1085],
        [-0.3384, -0.0630, -0.2433,  2.8393],
        [-0.2377,  0.6507,  8.2378,  8.7704]])

In [16]:
gradf(x)

tensor([[32.5879, -0.3687,  1.0148,  0.1085],
        [-0.3384, -0.0630, -0.2433,  2.8393],
        [-0.2377,  0.6507,  8.2378,  8.7704]], grad_fn=<AddBackward0>)

In [28]:
x = V(t.ones(1))
b = V(t.rand(1), requires_grad=True)
w = V(t.rand(1), requires_grad=True)
y = w * x
z = y + b

In [21]:
x.requires_grad, b.requires_grad, w.requires_grad, y.requires_grad, z.requires_grad

(False, True, True, True, True)

In [22]:
z.grad_fn

In [23]:
z.grad_fn.next_functions

((<MulBackward0 at 0x29332ce6820>, 0), (<AccumulateGrad at 0x29332ce6d60>, 0))

In [24]:
z.grad_fn.next_functions[0][0] == y.grad_fn

True

In [29]:
z.backward(retain_graph=True)
w.grad, b.grad

(tensor([1.]), tensor([1.]))

In [30]:
z.backward()

In [31]:
w.grad

tensor([2.])

In [1]:
import torch as t
from torch import nn
from torch.autograd import Variable as V

class Linear(nn.Module):
    def __init__(self, in_features, out_features):
        super(Linear, self).__init__()
        self.w = nn.Parameter(t.randn(in_features, out_features))
        self.b = nn.Parameter(t.randn(out_features))

    def forward(self, x):
        x = x.mm(self.w)
        return x + self.b.expand_as(x)

In [3]:
layer = Linear(4, 3)
input = V(t.randn(2, 4))
output = layer(input)
output

tensor([[-0.1679,  0.7091, -1.3501],
        [-0.8261, -0.1883, -0.0355]], grad_fn=<AddBackward0>)

In [4]:
for name, parameter in layer.named_parameters():
    print(name, parameter)

w Parameter containing:
tensor([[ 0.9024, -0.4350,  0.3230],
        [-1.0225, -1.4166, -0.4801],
        [-0.3918,  0.2172,  0.1490],
        [-0.6619, -0.9720,  0.9011]], requires_grad=True)
b Parameter containing:
tensor([-0.5261, -0.6881, -0.2063], requires_grad=True)


In [5]:
class Perceptron(nn.Module):
    def __init__(self, in_features, hidden_features, out_features):
        super(Perceptron, self).__init__()
        self.layer1 = Linear(in_features,
                             hidden_features)  # 此处的 Linear 是前面定义的全连接层
        self.layer2 = Linear(hidden_features, out_features)

    def forward(self, x):
        x = self.layer1(x)
        x = t.sigimoid(x)
        return self.layer2(x)


perceptron = Perceptron(3, 4, 1)
for name, param in perceptron.named_parameters():
    print(name, param.size())

layer1.w torch.Size([3, 4])
layer1.b torch.Size([4])
layer2.w torch.Size([4, 1])
layer2.b torch.Size([1])


### LeNet

In [9]:
import torch as t
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable as V


class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        
        # 卷积
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        
        # 全连接层
        self.fc1 = nn.Linear(16*5*5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
        
    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        
        x = x.view(x.size()[0], -1)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        
        return x


net = Net()
net
        
        

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)

In [10]:
params = list(net.parameters())
len(params)

10

In [11]:
for name, parameters in net.named_parameters():
    print(name, ':', parameters.size())

conv1.weight : torch.Size([6, 1, 5, 5])
conv1.bias : torch.Size([6])
conv2.weight : torch.Size([16, 6, 5, 5])
conv2.bias : torch.Size([16])
fc1.weight : torch.Size([120, 400])
fc1.bias : torch.Size([120])
fc2.weight : torch.Size([84, 120])
fc2.bias : torch.Size([84])
fc3.weight : torch.Size([10, 84])
fc3.bias : torch.Size([10])


In [12]:
input = V(t.randn(1, 1, 32, 32))  # 定义输入
out = net(input)
out.size()  # 输出的形状

torch.Size([1, 10])

In [13]:
net.zero_grad()  # 所有参数的梯度清零
out.backward(V(t.ones(1, 10)))  # 反向传播

In [15]:
output = net(input)  # net(input)的输出的形状是(1,10)
target = V(t.arange(0, 10)).view(1, 10).float()
criterion = nn.MSELoss()
loss = criterion(output, target)
loss

tensor(28.6623, grad_fn=<MseLossBackward0>)

In [16]:
net.zero_grad()  # 清空梯度
print('反向传播之前 conv1.bias的梯度')
print(net.conv1.bias.grad)
loss.backward()
print('反向传播之后 conv1.bias的梯度')

反向传播之前 conv1.bias的梯度
tensor([0., 0., 0., 0., 0., 0.])
反向传播之后 conv1.bias的梯度


In [17]:
import torch.optim as optim

optimizer = optim.SGD(net.parameters(), lr=0.01)

optimizer.zero_grad()  # 清空梯度

output = net(input)
loss = criterion(output, target)

loss.backward()

optimizer.step()  # 更新参数

In [18]:
inp = V(t.randn(2, 3))
linear = nn.Linear(3, 4)
h = linear(inp)
h


tensor([[ 0.0320,  0.6402,  1.1871,  0.1473],
        [ 0.0420,  0.1913,  0.5983, -0.1126]], grad_fn=<AddmmBackward0>)

In [20]:
bn = nn.BatchNorm1d(4)
bn.weight.data = t.ones(4) * 4
bn.bias.data = t.zeros(4)
bn_out = bn(h)
bn_out.mean(0), bn_out.var(0, unbiased=False)

(tensor([ 0.0000e+00,  0.0000e+00, -9.5367e-07,  2.3842e-07],
        grad_fn=<MeanBackward1>),
 tensor([11.3999, 15.9968, 15.9982, 15.9905], grad_fn=<VarBackward0>))

In [21]:
dropout = nn.Dropout(0.5)
o = dropout(bn_out)
bn_out, o


(tensor([[-3.3764,  3.9996,  3.9998,  3.9988],
         [ 3.3764, -3.9996, -3.9998, -3.9988]],
        grad_fn=<NativeBatchNormBackward0>),
 tensor([[-0.0000,  0.0000,  7.9995,  0.0000],
         [ 0.0000, -7.9992, -0.0000, -0.0000]], grad_fn=<MulBackward0>))

In [22]:
net1 = nn.Sequential()
net1.add_module('conv', nn.Conv2d(3, 3, 3))
net1.add_module('batchnorm', nn.BatchNorm2d(3))
net1.add_module('activation_layer', nn.ReLU())

net2 = nn.Sequential(nn.Conv2d(3, 3, 3), nn.BatchNorm2d(3), nn.ReLU())

from collections import OrderedDict
net3 = nn.Sequential(
    OrderedDict([('conv1', nn.Conv2d(3, 3, 3)), 
                 ('bn1', nn.BatchNorm2d(3)), 
                 ('relu', nn.ReLU())])
)

In [23]:
net1 

Sequential(
  (conv): Conv2d(3, 3, kernel_size=(3, 3), stride=(1, 1))
  (batchnorm): BatchNorm2d(3, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (activation_layer): ReLU()
)

In [27]:
embedding = nn.Embedding(4, 5)
embedding.weight.data = t.arange(0, 20).view(4, 5)
embedding.weight

Parameter containing:
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]], requires_grad=True)

In [30]:
with t.no_grad():
    inp = V(t.arange(3, 0, -1)).long()
    out = embedding(inp)
    print(out)

tensor([[15, 16, 17, 18, 19],
        [10, 11, 12, 13, 14],
        [ 5,  6,  7,  8,  9]])


In [31]:
score = V(t.randn(3, 2))
label = V(t.Tensor([1, 0, 1])).long()

criterion = nn.CrossEntropyLoss()
loss = criterion(score, label)
loss


tensor(0.8446)

In [32]:
import torch as t
from torch import nn
from torch.autograd import Variable as V

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.features = nn.Sequential(
            nn.Conv2d(3, 6, 5),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),
            nn.Conv2d(6, 16, 5),
            nn.ReLU(),
            nn.MaxPool2d(2, 2)
        )

        self.classifier = nn.Sequential(
            nn.Linear(16*5*5, 120),
            nn.ReLU(),
            nn.Linear(120, 84),
            nn.ReLU(),
            nn.Linear(84, 10)
        )
    
    def forward(self, x):
        x = self.features(x)
        x = x.view(-1, 16*5*5)
        x = self.classifier(x)
        return x
    
net = Net()
    

In [33]:
from torch import optim

optimizer = optim.SGD(params=net.parameters(), lr=1)
optimizer.zero_grad()  # 梯度清零

inp = V(t.rand(1, 3, 32, 32))
output = net(inp)
output.backward(output)

optimizer.step()  # 更新参数

##### 针对不同的层设定不同的lr

In [37]:
special_layers = nn.ModuleList([net.classifier[0], net.classifier[3]])
special_layers_params = list(map(id, special_layers.parameters()))

print(special_layers_params)

# 筛选出不属于特殊层的层
base_params = filter(lambda p: id(p) not in special_layers_params, net.parameters())

print(base_params)

# 对于特殊层和非特殊层设定不同的lr
optimizer = t.optim.SGD([{ 'params': base_params},
                            {'params': special_layers.parameters(), 'lr': 0.01}
                            ], lr=0.1)



[1687739240912, 1687739241312]


In [44]:
net.classifier[0]

Linear(in_features=400, out_features=120, bias=True)

In [49]:
# 只为两个全连接层设置较大的学习率，其余层的学习率较小
special_layers = nn.ModuleList([net.classifier[0], net.classifier[3]])
special_layers_params = list(map(id, special_layers.parameters()))  # 得到特殊层的 id

# 筛选出不属于特殊层的层
base_params = filter(lambda p: id(p) not in special_layers_params,
                     net.parameters())

# 对于特殊层和非特殊层设定不同的 lr
optimizer = t.optim.SGD([{
    'params': base_params
}, {
    'params': special_layers.parameters(),
    'lr': 0.01
}],
                        lr=0.001)

SGD (
Parameter Group 0
    dampening: 0
    foreach: None
    lr: 0.1
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0

Parameter Group 1
    dampening: 0
    foreach: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [50]:
import torch as t
from torch import nn
from torch.nn import init
linear = nn.Linear(3, 4)

t.manual_seed(1)
# 等价于 linear.weight.data.normal_(0, std)
init.xavier_normal_(linear.weight)  #

Parameter containing:
tensor([[ 0.3535,  0.1427,  0.0330],
        [ 0.3321, -0.2416, -0.0888],
        [-0.8140,  0.2040, -0.5493],
        [-0.3010, -0.4769, -0.0311]], requires_grad=True)

## 处理数据

In [58]:
import sys
import os

image_path = "DogsCats\\train_s"
os.path.isdir(image_path)


True

In [59]:
import os

imgs = os.listdir(image_path)
for img in imgs:
    print(img)

cat.0.jpg
cat.1.jpg
cat.10.jpg
cat.11.jpg
cat.12.jpg
cat.13.jpg
cat.2.jpg
cat.3.jpg
cat.4.jpg
cat.5.jpg
cat.6.jpg
cat.7.jpg
cat.8.jpg
cat.9.jpg


In [60]:
import os
import torch as t
import numpy as np
from PIL import Image
from torch.utils import data

class DogCat(data.Dataset):
    def __init__(self, root):
        imgs = os.listdir(root)
        self.imgs = [os.path.join(root, img) for img in imgs]
        
    def __getitem__(self, index):
        img_path = self.imgs[index]
        
        label = 1 if 'dog' in img_path.split('/')[-1] else 0
        
        pil_img = Image.open(img_path)
        array = np.asarray(pil_img)
        data = t.from_numpy(array)
        return data, label
    
dataset = DogCat(image_path)
for img, label in dataset:
    print(img.size(), img.float().mean(), label)
        

torch.Size([374, 500, 3]) tensor(119.7826) 0
torch.Size([280, 300, 3]) tensor(71.6653) 0
torch.Size([499, 489, 3]) tensor(108.7773) 0
torch.Size([410, 431, 3]) tensor(110.0135) 0
torch.Size([224, 300, 3]) tensor(101.3933) 0
torch.Size([315, 499, 3]) tensor(153.7032) 0
torch.Size([396, 312, 3]) tensor(131.8400) 0
torch.Size([414, 500, 3]) tensor(156.6921) 0
torch.Size([375, 499, 3]) tensor(96.8243) 0
torch.Size([144, 175, 3]) tensor(166.6151) 0
torch.Size([303, 400, 3]) tensor(129.1319) 0
torch.Size([499, 495, 3]) tensor(90.0335) 0
torch.Size([345, 461, 3]) tensor(109.3431) 0
torch.Size([425, 320, 3]) tensor(158.8270) 0


C:\Users\14419\AppData\Local\Temp\ipykernel_10552\1047285573.py:19: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:178.)
  data = t.from_numpy(array)


In [63]:
import os
from PIL import Image
import numpy as np
from torchvision import transforms as T

transform = T.Compose([
    T.Resize(224),
    T.CenterCrop(224),
    T.ToTensor(),
    T.Normalize(mean=[.5, .5, .5], std=[.5, .5, .5])
])

class DogCat(data.Dataset):
    def __init__(self, root, transform=None):
        imgs = os.listdir(root)
        self.imgs = [os.path.join(root, img) for img in imgs]
        self.transform = transform
        
    def __getitem__(self, index):
        img_path = self.imgs[index]
        label = 1 if 'dog' in img_path.split('/')[-1] else 0
        data = Image.open(img_path)
        if self.transform:
            data = self.transform(data)
        return data, label
    
    def __len__(self):
        return len(self.imgs)
    

dataset = DogCat(image_path, transform=transform)
img, label = dataset[0]
for img, label in dataset:
    print(img.size(), label)



torch.Size([3, 224, 224]) 0
torch.Size([3, 224, 224]) 0
torch.Size([3, 224, 224]) 0
torch.Size([3, 224, 224]) 0
torch.Size([3, 224, 224]) 0
torch.Size([3, 224, 224]) 0
torch.Size([3, 224, 224]) 0
torch.Size([3, 224, 224]) 0
torch.Size([3, 224, 224]) 0
torch.Size([3, 224, 224]) 0
torch.Size([3, 224, 224]) 0
torch.Size([3, 224, 224]) 0
torch.Size([3, 224, 224]) 0
torch.Size([3, 224, 224]) 0


In [69]:
from torchvision.datasets import ImageFolder

image_path = 'DogsCats\\train_s'

dataset = ImageFolder(image_path)
print(os.path.isdir(image_path))

dataset.class_to_idx

FileNotFoundError: Couldn't find any class folder in DogsCats\train_s.

In [70]:
from torch.utils.data import DataLoader

dataloader = DataLoader(dataset, batch_size=3, shuffle=True, num_workers=0, drop_last=False)


dataiter = iter(dataloader)
imgs, labels = next(dataiter)

imgs.size()


torch.Size([3, 3, 224, 224])

##### 处理损坏图片

In [79]:
class NewDogCat(DogCat):
    def __getitem__(self, index):
        try:
            return super(NewDogCat, self).__getitem__(index)
        except:
            return None, None

from torch.utils.data.dataloader import default_collate # 导入默认拼接方式

def my_collate_fn(batch):
    batch = list(filter(lambda x: x[0] is not None, batch))
    return default_collate(batch)

dataset = NewDogCat(image_path, transform=transform)
dataset[6][0].size()

torch.Size([3, 224, 224])

In [82]:
dataloader = DataLoader(dataset, 2, collate_fn=my_collate_fn, num_workers=0, shuffle=True)

for batch_datas, batch_labels in dataloader:
    print(batch_datas.size(), batch_labels.size())


torch.Size([2, 3, 224, 224]) torch.Size([2])
torch.Size([2, 3, 224, 224]) torch.Size([2])
torch.Size([2, 3, 224, 224]) torch.Size([2])
torch.Size([2, 3, 224, 224]) torch.Size([2])
torch.Size([2, 3, 224, 224]) torch.Size([2])
torch.Size([2, 3, 224, 224]) torch.Size([2])
torch.Size([1, 3, 224, 224]) torch.Size([1])


#### 数据采样

In [86]:
dataset = DogCat(image_path, transform=transform)

weights = [2 if label==1 else 1 for data, label in dataset]
weights
 

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2]

In [90]:
from torch.utils.data.sampler import WeightedRandomSampler

sampler = WeightedRandomSampler(weights, num_samples=8, replacement=True)
dataloader = DataLoader(dataset, batch_size=4, sampler=sampler)

for datas, labels in dataloader:
    print(labels.tolist())



[0, 0, 1, 0]
[0, 0, 0, 0]
