In [1]:
import torch as t

In [2]:
a = t.Tensor(2, 3)
a

tensor([[3.2721e+21, 1.0624e+21, 5.2708e-08],
        [2.1159e-07, 5.4174e-05, 5.3696e-05]])

In [3]:
b = t.tensor([[1, 2, 3], [2, 3, 4]])
b.tolist()

[[1, 2, 3], [2, 3, 4]]

In [4]:
print(f'type(b): {type(b)}')

type(b): <class 'torch.Tensor'>


In [5]:
b.numel()

6

In [6]:
c = t.Tensor(b.size())
c

tensor([[1.6926e+22, 5.4366e+22, 1.6898e-04],
        [8.5458e-07, 2.1121e+20, 1.7000e+22]])

### 调整tensor形状

In [7]:
a = t.arange(0, 6)
a

tensor([0, 1, 2, 3, 4, 5])

In [8]:
b = a.view(2, 3)
print(f'a: {a}\n\n b: {b}')

a: tensor([0, 1, 2, 3, 4, 5])

 b: tensor([[0, 1, 2],
        [3, 4, 5]])


In [9]:
c = a.view(-1, 3)
print(f'a: {a}\n\nc: {c}')

a: tensor([0, 1, 2, 3, 4, 5])

c: tensor([[0, 1, 2],
        [3, 4, 5]])


In [10]:
a[1] = 0
print(f'a: {a}\n\nb: {b}\n\nc: {c}')

a: tensor([0, 0, 2, 3, 4, 5])

b: tensor([[0, 0, 2],
        [3, 4, 5]])

c: tensor([[0, 0, 2],
        [3, 4, 5]])


In [11]:
d = b.unsqueeze(1)
d, d.size()

(tensor([[[0, 0, 2]],
 
         [[3, 4, 5]]]),
 torch.Size([2, 1, 3]))

In [12]:
e = b.view(1, 1, 2, 1, 3)
f = e.squeeze(0)
f, f.size()
# e, e.size()

(tensor([[[[0, 0, 2]],
 
          [[3, 4, 5]]]]),
 torch.Size([1, 2, 1, 3]))

In [13]:
e.squeeze()

tensor([[0, 0, 2],
        [3, 4, 5]])

In [14]:
e = b.view(1, 1, 2, 1, 3)
f = e.squeeze(0)  # 压缩第0维的“1”，某一维度为“1”才能压缩，如果第0维的维度是“2”如(2,1,1,1,3)则无法亚索第0维
f, f.size()

(tensor([[[[0, 0, 2]],
 
          [[3, 4, 5]]]]),
 torch.Size([1, 2, 1, 3]))

In [15]:
a = t.arange(0, 16).view(4, 4)
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [16]:
index = t.LongTensor([[0, 1, 2, 3]])
print(f'index: {index}')
a.gather(0, index)

index: tensor([[0, 1, 2, 3]])


tensor([[ 0,  5, 10, 15]])

In [17]:
# 选取反对角线上的元素
index = t.LongTensor([[3, 2, 1, 0]])  # .t()是转置
a.gather(0, index)

tensor([[12,  9,  6,  3]])

In [18]:
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [19]:
x = t.arange(0, 27).view(3, 3, 3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])

In [20]:
x[[1, 2], [1, 2], [2, 0]]  # x[1,1,2] 和 x[2,2,0]

tensor([14, 24])

In [21]:
t.set_default_tensor_type('torch.DoubleTensor')

In [22]:
a = t.Tensor(2, 3)
a, a.type()

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 'torch.DoubleTensor')

In [23]:
b = a.int()
b, b.type()

(tensor([[0, 0, 0],
         [0, 0, 0]], dtype=torch.int32),
 'torch.IntTensor')

In [24]:
c = a.type_as(b)
c, c.type()

(tensor([[0, 0, 0],
         [0, 0, 0]], dtype=torch.int32),
 'torch.IntTensor')

In [25]:
d = a.new(2, 3)
d, d.type()

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 'torch.DoubleTensor')

In [26]:
t.set_default_tensor_type('torch.FloatTensor')  # 恢复之前的默认设置

In [27]:
b = t.ones(2, 3)
a = t.zeros(2, 3)
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [28]:
b.sum(dim=0), b.sum(dim=0, keepdim=True)  # 前者输出形状是(3)，后者输出形状是(1,3)

(tensor([2., 2., 2.]), tensor([[2., 2., 2.]]))

In [29]:
a = t.arange(0, 6).view(2, 3)
a

tensor([[0, 1, 2],
        [3, 4, 5]])

In [30]:
a.cumsum(dim=1)

tensor([[ 0,  1,  3],
        [ 3,  7, 12]])

### tensor & ndarray

In [31]:
import numpy as np

a = np.ones((2, 3), dtype=np.float32)
a

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [32]:
b = t.from_numpy(a)
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [33]:
b = t.Tensor(a)
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [34]:
a[0, 1] = 100
c = b.numpy()
c

array([[  1., 100.,   1.],
       [  1.,   1.,   1.]], dtype=float32)

In [35]:
a = t.ones(3, 2)
b = t.zeros(2, 3, 1)

In [36]:
b, b.expand(2, 3, 2)

(tensor([[[0.],
          [0.],
          [0.]],
 
         [[0.],
          [0.],
          [0.]]]),
 tensor([[[0., 0.],
          [0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.],
          [0., 0.]]]))

In [37]:
a.unsqueeze(0).expand(2, 3, 2), a.shape

(tensor([[[1., 1.],
          [1., 1.],
          [1., 1.]],
 
         [[1., 1.],
          [1., 1.],
          [1., 1.]]]),
 torch.Size([3, 2]))

In [39]:
print(t.cuda.is_available())

True


## Autograd


### Variable

In [2]:
import torch as t
from torch.autograd import Variable as V

In [3]:
a = V(t.ones(3, 4), requires_grad=True)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], requires_grad=True)

In [4]:
b = V(t.zeros(3, 4))
b

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
c = a.add(b)
c

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], grad_fn=<AddBackward0>)

In [6]:
a.requires_grad, b.requires_grad, c.requires_grad

(True, False, True)

In [9]:
d = c.sum()
d.backward()

In [10]:
a.grad

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [11]:
a.is_leaf, b.is_leaf, c.is_leaf

(True, True, False)

In [12]:
c.retain_grad()
c.grad is None

True

In [13]:
c

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], grad_fn=<AddBackward0>)

In [14]:
def f(x):
    y = x**2 * t.exp(x)
    return y

def gradf(x):
    dx = 2*x*t.exp(x) + x**2*t.exp(x)
    return dx

x = V(t.randn(3, 4), requires_grad=True)
y = f(x)
y

tensor([[1.4831e+01, 3.6706e-01, 1.3936e-01, 2.6639e-03],
        [3.9522e-01, 5.3491e-01, 2.0241e-02, 6.5490e-01],
        [4.6668e-01, 6.7475e-02, 2.7539e+00, 2.9840e+00]],
       grad_fn=<MulBackward0>)

In [15]:
y_grad_variables = t.ones(y.size())
y.backward(y_grad_variables)
x.grad

tensor([[32.5879, -0.3687,  1.0148,  0.1085],
        [-0.3384, -0.0630, -0.2433,  2.8393],
        [-0.2377,  0.6507,  8.2378,  8.7704]])

In [16]:
gradf(x)

tensor([[32.5879, -0.3687,  1.0148,  0.1085],
        [-0.3384, -0.0630, -0.2433,  2.8393],
        [-0.2377,  0.6507,  8.2378,  8.7704]], grad_fn=<AddBackward0>)